name: Go Release

on:
  push:
    tags:
      - '*' # 当有新的 tag 被 push 时触发
  workflow_dispatch: # 允许手动触发
      

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 允许创建 release
      actions: write # 允许上传 assets

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: |
        TAG="${GITHUB_REF#refs/tags/}"
        echo "build version:" $TAG
        go build -ldflags "-X main.version=$TAG" -tags=release -o http_proxy .
      
    - name: Get tag description and write release notes
      run: |
        tag="${GITHUB_REF#refs/tags/}"
        desc=$(git tag -l --format='%(contents)' $tag)
        echo "description: $desc"
        echo "Release notes for tag $tag" > release_notes.txt
        echo "" >> release_notes.txt
        echo "$desc" >> release_notes.txt

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body_path: release_notes.txt
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./http_proxy  #  可执行文件的路径
        asset_name: http_proxy #  Release 中显示的文件名
        asset_content_type: application/octet-stream